@startuml
skinparam monochrome true

scale 1.5
left to right direction

[*] --> Initiate
Initiate --> Reserve: User confirms
Reserve --> Capture: Merchant captures
Reserve --> Cancel: Merchant cancels (potentially on behalf of the user)
Capture --> Refund: Merchant refunds
Capture --> [*]
Cancel --> [*]
Refund --> [*]
Initiate --> Cancel: User cancels, or timeout
@enduml
