@startuml
skinparam monochrome true

scale 1.5
left to right direction

[*] --> Initiate
Initiate --> Reserve
Reserve --> Capture
Reserve --> Cancel
Capture --> Refund
Capture --> [*]
Cancel --> [*]
Refund --> [*]
Initiate --> Cancel
@enduml
